name: Frontend to EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CLUSTER_NAME: nodejs-frontend-cluster
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::643683863113:role/github-terraform-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      
    - name: Deploy to EKS
      run: |
        kubectl get deployments -A
        kubectl get pods -A
